spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DBNAME}
    username:
      ${DB_USERNAME} 
    password:
      ${DB_PASSWORD} 
  jpa:
    hibernate:
      ddl-auto:
        update
server:
  port: ${SERVER_PORT}

